[local]
localhost ansible_connection=local

[mongo]
mongo.dcinema.online

[mysql]
mysql.dcinema.online

[redis]
redis.dcinema.online

[rabbitmq]
rabbitmq.dcinema.online

[cart]
cart.dcinema.online

[catalogue]
catalogue.dcinema.online

[user]
user.dcinema.online

[shipping]
shipping.dcinema.online

[payment]
payment.dcinema.online

[frontend]
frontend.dcinema.online
