  - name: enable node:20
    command: dnf module enable nodejs:20 -y
  
  - name: Install Node
    package:
     name: nodejs
     state: present
  
  - name: create roboshop system user
    user:
      name: roboshop
      system: true
      home: /app
      shell: /bin/nologin
      comment: "roboshop system user"
  # need to create a directory and download code
  # if directory present then delete and create againg and download
  - name: Delete a directory
    ansible.builtin.file:
      path:  /app 
      state: absent

  - name: delete catalogue.zip in tmp
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: Create a directory if doen't exists
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: Download catalogue
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
     dest: /tmp/catalogue.zip

  - name: unzip catalogue
    ansible.builtin.unarchive:
     src:  /tmp/catalogue.zip
     dest: /app
     remote_src: true
  
  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Copy file to /etc/file.conf
    ansible.builtin.template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service

  - name: Copy mongo repo
    ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo
  
  - name: Install mongo db client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present
  # load user data
  - name: check catalogue schema exist or not
    shell:  mongosh --host "{{ MONGO_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags: 
    - mongo  
  
  - name: print catalogue_output
    debug:
      msg: "{{ catalogue_output }}"
    tags: 
    - mongo
    # to run this particular task we are using tags, use -t mongo at the end of command
  - name: Load products
    shell: mongosh --host {{ MONGO_HOST }} </app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    #stdout is in double qoutes so we are converting it to int
    tags:
    - mongo

  - name: Restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
    ansible.builtin.systemd_service:
     name: catalogue
     #state: restarted
     daemon_reload: true
    #when: unit_file.change

  - name: start and enable catalongue
    service:
      name: catalogue
      state: restarted
      enabled: true
 